export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const SAVE_WEATHER_DATA = 'SAVE_WEATHER_DATA';

export const SAVE_PLACES = 'SAVE_PLACES';
export const GET_PLACES = 'GET_PLACES';
export const SET_PLACE_LOADING = 'SET_PLACE_LOADING';
export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';

export const FILTER_CITY = 'FILTER_CITY';
export const FIREBASE_FILTER_CITY = 'FIREBASE_FILTER_CITY';
export const FIREBASE_FILTER_USER = 'FIREBASE_FILTER_USER';
export const SET_FILTER_CITIES = 'SET_FILTER_CITIES';
export const SET_FILTER_USERS = 'SET_FILTER_USERS';

export const TEST_CHANGE_PROPS = 'TEST_CHANGE_PROPS';

export const GET_CURRENT_PLACE = 'GET_CURRENT_PLACE';
export const UPDATE_CURRENT_PLACE_TO_FIREBASE = "UPDATE_CURRENT_PLACE_TO_FIREBASE"

export const SET_USERS_IN_MAP = "SET_USERS_IN_MAP"

export const CREATE_GROUP = "CREATE_GROUP"
export const GET_GROUPS = "GET_GROUPS"
export const SET_GROUPS = "SET_GROUPS"

export const ADD_FRIEND = "ADD_FRIEND"
export const SUBSCRIBE = "SUBSCRIBE"

export const REQUEST_LOCATION = "REQUEST_LOCATION"
export const CREATE_CHANNEL = "CREATE_CHANNEL"
export const REJECT_JOIN_CHANNEL = "REJECT_JOIN_CHANNEL"
export const ACCEPT_JOIN_CHANNEL = "ACCEPT_JOIN_CHANNEL"
export const UN_SUBSCRIBE_CHANNEL = "UN_SUBSCRIBE_CHANNEL"
export const LEAVE_CHANNEL = "LEAVE_CHANNEL"






