export const FIREBASE_FILTER_USER = 'FIREBASE_FILTER_USER';
export const SET_FILTER_USERS = 'SET_FILTER_USERS';
export const GET_CURRENT_PLACE = 'GET_CURRENT_PLACE';
export const UPDATE_CURRENT_PLACE_TO_FIREBASE = "UPDATE_CURRENT_PLACE_TO_FIREBASE"
export const SET_USER_IN_MAP = "SET_USER_IN_MAP"
export const ADD_FRIEND = "ADD_FRIEND"
export const SUBSCRIBE = "SUBSCRIBE"
export const REQUEST_LOCATION = "REQUEST_LOCATION"
export const CREATE_CHANNEL = "CREATE_CHANNEL"
export const REJECT_JOIN_CHANNEL = "REJECT_JOIN_CHANNEL"
export const ACCEPT_JOIN_CHANNEL = "ACCEPT_JOIN_CHANNEL"
export const UN_SUBSCRIBE_CHANNEL = "UN_SUBSCRIBE_CHANNEL"
export const LEAVE_CHANNEL = "LEAVE_CHANNEL"

export const SAGA_FACEBOOK_GET_ACCESS_TOKEN = "SAGA_FACEBOOK_GET_ACCESS_TOKEN"






